SCREEN_WIDTH = 1080
SCREEN_HEIGHT = 900
BG_COLOR = [213, 39, 106, 1]
PAD_COLOR = [255, 255, 255, 1]
BALL_COLOR = [255, 255, 255, 1]
SCORE_COLOR = [255, 255, 255, 1]
PAD_HEIGHT = 800
PAD_WIDTH = 20
BALL_RADIUS = 50
